# Generated by Django 3.0.3 on 2020-02-19 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='procurado_em',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0)),
        ),
    ]
