# Generated by Django 3.0.3 on 2020-02-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0002_auto_20200212_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermosParaBusca',
            new_name='TermoParaBusca',
        ),
    ]
