# Generated by Django 3.0.3 on 2020-02-19 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0002_auto_20200219_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='procurado_em',
            field=models.DateTimeField(default=datetime.datetime(1001, 1, 1, 3, 6, tzinfo=utc)),
        ),
    ]
