# Generated by Django 3.0.3 on 2020-02-13 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0003_auto_20200212_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='juapp.Diario')),
            ],
            options={
                'ordering': ['diario', 'pagina'],
            },
        ),
        migrations.AlterModelOptions(
            name='horarioparabusca',
            options={'ordering': ['local_para_busca', 'horario'], 'verbose_name_plural': 'Horarios para busca'},
        ),
        migrations.AlterModelOptions(
            name='localparabusca',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Locais para busca'},
        ),
        migrations.AlterModelOptions(
            name='termoparabusca',
            options={'ordering': ['local_para_busca', 'string'], 'verbose_name_plural': 'Termos para busca'},
        ),
        migrations.AddField(
            model_name='localparabusca',
            name='logo',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
