# Generated by Django 3.0.3 on 2020-02-16 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juapp', '0008_auto_20200213_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termoparabusca',
            options={'ordering': ['local_para_busca', 'string'], 'permissions': [('all', 'Can change the status of tasks')], 'verbose_name_plural': 'Termos para busca'},
        ),
        migrations.RemoveField(
            model_name='localparabusca',
            name='dias_para_busca',
        ),
        migrations.AddField(
            model_name='termoparabusca',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termos_para_busca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HorarioParaBusca',
        ),
    ]
