# Generated by Django 3.0.3 on 2020-02-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0009_auto_20200216_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoparabusca',
            name='proprietario',
        ),
    ]
