# Generated by Django 3.0.3 on 2020-02-17 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0013_auto_20200216_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termoparabusca',
            options={'ordering': ['local_para_busca', 'string'], 'verbose_name_plural': 'Termos para busca'},
        ),
        migrations.AddField(
            model_name='termoparabusca',
            name='desde',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
