# Generated by Django 3.0.3 on 2020-02-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0014_auto_20200217_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='localparabusca',
            name='method',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
