# Generated by Django 3.0.3 on 2020-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0015_localparabusca_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localparabusca',
            name='method',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
