# Generated by Django 3.0.3 on 2020-02-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0017_pagina_creado_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagina',
            old_name='creado_em',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='diario',
            name='termos_buscados',
        ),
        migrations.AlterField(
            model_name='diario',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='localparabusca',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
