# Generated by Django 3.0.3 on 2020-02-18 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0019_auto_20200218_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='termoparabusca',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
