# Generated by Django 3.0.3 on 2020-02-11 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.FileField(upload_to='')),
                ('URL', models.URLField()),
                ('LIDO', models.BooleanField(default=False)),
                ('QUANTIDADE_TOTAL', models.IntegerField()),
                ('DATA', models.DateField(blank=True, default=datetime.datetime.now)),
                ('BAIXADO_EM', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('PROCURADO_EM', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAGINA', models.IntegerField()),
                ('QUANTIDADE', models.IntegerField()),
                ('DIARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PAGES', to='juapp.Diario')),
            ],
        ),
    ]
