# Generated by Django 3.0.3 on 2020-02-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0007_pagina_termo_buscado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='termo_buscado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='juapp.TermoParaBusca'),
        ),
    ]
