# Generated by Django 3.0.3 on 2020-02-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juapp', '0004_auto_20200212_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localparabusca',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
